[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
